/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/island.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.GuardChairGeo_25.geometry}
        material={materials.GuardChairMaterial}
        position={[-5.78, -0.6, 8.45]}
        rotation={[Math.PI / 2, 0, -0.17]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.OrangeTowelGeo_52.geometry}
        material={materials.OrangeTowel}
        position={[2.68, -0.55, 6.93]}
        rotation={[Math.PI / 2, 0, -2.27]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.RedTowelGeo_55.geometry}
        material={materials.ColourfulTowel_BaseColor_Mat}
        position={[6.95, -0.57, 7.72]}
        rotation={[Math.PI / 2, 0, -2.27]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.IslandModel_111.geometry}
        material={materials.blinn4}
        position={[0.6, -0.9, 5.3]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Rock02GrassGeo_117.geometry}
        material={materials.Rock02WithGrassMat}
        position={[10.3, -0.61, 0.5]}
        rotation={[Math.PI / 2, 0, 0.7]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Umbrellas.geometry}
        material={materials.UmbrellaMaterial}
        position={[-2.24, -0.4, 8.15]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.BlueTowels.geometry}
        material={materials.BlueTowel}
        position={[-1.46, -0.56, 8.56]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.GreenTowels.geometry}
        material={materials.GreenTowel}
        position={[1.89, -0.57, 10.59]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Floaters.geometry}
        material={materials.FloaterMaterial}
        position={[4.27, -0.45, 9.07]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.RedSurfboards.geometry}
        material={materials.RedSurfboard_Material}
        position={[-7.36, -0.5, 8.7]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[-3.16, -0.2, -0.28]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Trees_1.geometry} material={materials.LeafMaterial} />
        <mesh geometry={nodes.Trees_2.geometry} material={materials.TreeMaterial} />
      </group>
      <mesh
        geometry={nodes.Rocks01WithGrass.geometry}
        material={materials.Rock01WithGrassMat}
        position={[-8.6, -1, 1.9]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Rocks01WithoutGrass.geometry}
        material={materials.Rock01NoGrassMat}
        position={[-17.7, -1.5, 0.8]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Rocks02WithoutGrass.geometry}
        material={materials.Rock02NoGrassMat}
        position={[18.2, -1.5, 0.4]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.BluePlastics.geometry}
        material={materials.BluePlasticMaterial}
        position={[-12.1, -0.46, 7.88]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.RedPlastics.geometry}
        material={materials.RedPlasticMaterial}
        position={[-10.98, -0.6, 9.71]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Beachballs.geometry}
        material={materials.BeachballMaterial}
        position={[-8.23, -0.43, 9.77]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.SeaShells.geometry}
        material={materials.ShellMaterial}
        position={[-2.59, -0.83, 13.15]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sandcastles.geometry}
        material={materials.SandCastleMaterial}
        position={[-11.18, -0.75, 7.69]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.WhiteSurfboards.geometry}
        material={materials.WhiteSurfBoard_Material}
        position={[13.5, -0.49, 5.8]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.WoodenSurfboards.geometry}
        material={materials.Wood_basecolor_Mat}
        position={[-7.68, -0.49, 5.18]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Starfishies.geometry}
        material={materials.StarfishMaterial}
        position={[13.06, -0.58, 8.31]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.GrassFoilages.geometry}
        material={materials.blinn1}
        position={[-2.7, 0.1, -0.1]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.BlueSurfboards.geometry}
        material={materials.BlueSurfboard_Material}
        position={[-8.15, -0.63, 4.79]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/island.glb')
